---
- name: Deploy Calculator
  hosts: localhost
  become: yes # Enable sudo
  # become_method: sudo # Explicitly use sudo
  become_user: root # Run tasks as root
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker image
      docker_image:
        name: preet1018/scientific-calculator:0.0.1
        source: pull

    - name: Run container
      docker_container:
        name: calculator
        image: preet1018/scientific-calculator:0.0.1
        state: started
        restart_policy: always
        interactive: true
        tty: true
        # stdin_open: true
